// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAE_dSHH577t3Zx_TZNvGOQtCQUPnVxhnk',
    appId: '1:58300775581:web:5c68e4f0d24c47d6052874',
    messagingSenderId: '58300775581',
    projectId: 'yojana-seva',
    authDomain: 'yojana-seva.firebaseapp.com',
    storageBucket: 'yojana-seva.firebasestorage.app',
    measurementId: 'G-8BD17XN0Z6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVSsuAs5ktx5irh0nMq2yrfbWyzUiSsFw',
    appId: '1:58300775581:android:8f0760f5a498d0ef052874',
    messagingSenderId: '58300775581',
    projectId: 'yojana-seva',
    storageBucket: 'yojana-seva.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCK_o0C67FGzDluTX8kS0WaK4qSJ4hNXao',
    appId: '1:58300775581:ios:efe8d363d872e915052874',
    messagingSenderId: '58300775581',
    projectId: 'yojana-seva',
    storageBucket: 'yojana-seva.firebasestorage.app',
    iosBundleId: 'com.example.yojanaSeva',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCK_o0C67FGzDluTX8kS0WaK4qSJ4hNXao',
    appId: '1:58300775581:ios:efe8d363d872e915052874',
    messagingSenderId: '58300775581',
    projectId: 'yojana-seva',
    storageBucket: 'yojana-seva.firebasestorage.app',
    iosBundleId: 'com.example.yojanaSeva',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAE_dSHH577t3Zx_TZNvGOQtCQUPnVxhnk',
    appId: '1:58300775581:web:6c27b7fdc9a1d42e052874',
    messagingSenderId: '58300775581',
    projectId: 'yojana-seva',
    authDomain: 'yojana-seva.firebaseapp.com',
    storageBucket: 'yojana-seva.firebasestorage.app',
    measurementId: 'G-RSK0L46WNL',
  );

}